obj-$(CONFIG_LGE_PM) += lge_monitor_thermal.o
obj-$(CONFIG_LGE_PM_CABLE_DETECTION) += lge_cable_detection.o
obj-$(CONFIG_LGE_PM_SMPL_COUNTER) += lge_smpl_count.o
obj-$(CONFIG_LGE_PM_CHARGING_CONTROLLER) += lge_charging_controller.o
obj-$(CONFIG_LGE_PM_CHARGING_SCENARIO) += lge_charging_scenario.o
obj-$(CONFIG_LGE_PM_UNIFIED_NODE) += lge_power_sysfs.o
obj-$(CONFIG_LGE_PM_PSEUDO_BATTERY) += lge_pseudo_batt.o
obj-$(CONFIG_MACH_LGE) += lge_gpio_debug.o lge_boost_bypass.o
