obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_MACH_LGE) += lge_gpio_debug.o lge_boost_bypass.o
obj-$(CONFIG_LGE_PM_CHARGING_CONTROLLER) += lge_charging_controller.o
obj-$(CONFIG_LGE_PM_CHARGING_SCENARIO) += lge_charging_scenario.o
obj-$(CONFIG_LGE_PM_PSEUDO_BATTERY) += lge_pseudo_batt.o